version: "2"
run:
  concurrency: 8
  go: 1.22.0
output:
  sort-order:
    - linter
    - file
    - severity
linters:
  default: none
  enable:
    - errcheck
    - sloglint
    - wrapcheck
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    sloglint:
      attr-only: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - .*\.gen\.go$
      - .*\.ridl$
      - vendor
      - tools
      - scripts
      - bin
      - .buildkite
      - etc
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/0xsequence/go-libs)
      custom-order: true
      no-lex-order: false
  exclusions:
    generated: lax
    paths:
      - .*\.gen\.go$
      - .*\.ridl$
      - vendor
      - tools
      - scripts
      - bin
      - .buildkite
      - etc
      - third_party$
      - builtin$
      - examples$
